default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: job_board_development
  username: postgres
  password:
  port: 5432
  host: db

test:
  <<: *default
  database: job_board_test
  username: postgres
  password:
  port: 5432
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
