default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: job_board_development
  port: 5432

test:
  <<: *default
  database: job_board_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
